[Python] Fix build without host unit test (#42034)
Since #41066 build without host unit test fails with:
```

../src/controller/python/matter/clusters/attribute.cpp:454:22: error: 'TestOnlyOverrideTimedRequestFieldTag' is not a member of 'chip::app::WriteClient'
  454 |         WriteClient::TestOnlyOverrideTimedRequestFieldTag{});
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Apply the common pattern where we return not implemented in case we build the
Matter SDK without `CONFIG_BUILD_FOR_HOST_UNIT_TEST` flag.